name: Notice                        # 플러그인의 이름
main: kr.kgaons.notice.Notice       # 플러그인의 메인 클래스
version: 1.0                                # 플러그인 버전

commands:
  확성기:                                   # 명령어 이름
    description: 확성기      # 명령어 설명